version: '3'

includes:
  tasks: .github/tasks

tasks:
  setup:
    desc: Setup repo environment
    deps:
      - tasks:setup
  update:
    desc: Run updates
    deps:
      - tasks:update
  scan:
    desc: Scan current repo
    cmds:
      - source .venv/bin/activate && tartufo --config .github/tartufo.toml scan-local-repo .
