---
version: "3"

includes:
  secrets: ../secrets
  direnv: direnv/Taskfile_{{OS}}.yml
  githubcli: githubcli/Taskfile_{{OS}}.yml
  cloudflared: cloudflared/Taskfile_{{OS}}.yml

tasks:
  setup:
    cmds:
      - task: pip
      - task: yarn
      # - task: githubcli:setup
      # - task: cloudflared:setup
      # - task: direnv:setup
      - task: secrets:setup
      - task: pre-commit
  virtualenv:
    cmds:
      - python3 -m venv .venv
    generates:
      - .venv/bin/activate
    status:
      - test -d .venv
      - test -f .venv/bin/activate
  pip-virtualenv:
    cmds:
      - task: virtualenv
      - source .venv/bin/activate && python3 -m pip install --require-virtualenv -r requirements.dev.txt
  pip:
    cmds:
      - task: pip-virtualenv
  pre-commit:
    cmds:
      - task: pip
      - pre-commit install -f
  yarn:
    cmds:
      - yarn install
    generates:
      - node_modules
    status:
      - test -d node_modules
  ansible:
    cmds:
      - task: pip
      - >-
        ansible-galaxy role install -r requirements.yml &&
        ansible-galaxy collection install -r requirements.yml
