version: '3'

includes:
  secrets: ../secrets
  direnv: direnv/Taskfile_{{OS}}.yml

tasks:
  setup:
    deps:
      - virtualenv
      - pip
      - direnv:install
      - secrets:setup
      - pre-commit
  virtualenv:
    cmds:
      - python3 -m venv .venv
    generates:
      - .venv
    status:
      - test -d .venv
  pip:
    deps:
      - virtualenv
    cmds:
      - .venv/bin/pip install -r requirements.dev.txt
  pre-commit:
    deps:
      - pip
    cmds:
      - .venv/bin/pre-commit install -f
