---
version: "3"

tasks:
  all:
    - task: markdown
    - task: yaml
    - task: json
  markdown:
    cmds:
      - >-
        prettier
        --config '.github/lint/.prettierrc.yaml'
        --ignore-path '.gitignore'
        --list-different
        --ignore-unknown
        --parser=markdown
        --write '*.md' '**/*.md'
    ignore_error: true
  yaml:
    cmds:
      - >-
        prettier
        --config '.github/lint/.prettierrc.yaml'
        --ignore-path '.gitignore'
        --list-different
        --ignore-unknown
        --parser=yaml
        --write
        './*.y*ml'
        './**/*.y*ml'
        './.github/**/*.y*ml'
    ignore_error: true
  json:
    cmds:
      - >-
        prettier
        --config '.github/lint/.prettierrc.yaml'
        --ignore-path '.gitignore'
        --list-different
        --ignore-unknown
        --parser=json
        --write '*.json'
        '**/*.json'
    ignore_error: true
