---
version: "3"

tasks:
  all:
    - task: markdown
    - task: yaml
  markdown:
    cmds:
      - >-
        prettier
        --ignore-path '.github/lint/.prettierignore'
        --config '.github/lint/.prettierrc.yaml'
        --list-different
        --ignore-unknown
        --parser=markdown
        --write '*.md' '**/*.md'
    ignore_error: true
  yaml:
    cmds:
      - >-
        prettier
        --ignore-path '.github/lint/.prettierignore'
        --config '.github/lint/.prettierrc.yaml'
        --list-different
        --ignore-unknown
        --parser=yaml
        --write '*.y*ml'
        '**/*.y*ml'
    ignore_error: true