---
version: "3"

tasks:
  all:
    - task: markdown
    - task: yaml
    - task: format

  markdown:
    cmds:
      - markdownlint -c '.github/lint/.markdownlint.yaml' *.md **/*.md
    ignore_errors: true
  
  yaml:
    cmds:
      - yamllint -c '.github/lint/.yamllint.yaml' .
    ignore_errors: true

  format:
    cmds:
      - prettier --ignore-path '.github/lint/.prettierignore' --config '.github/lint/.prettierrc.yaml' --check .
    ignore_errors: true