---
version: "3"

tasks:
  all:
    - task: markdown
    - task: yaml
    - task: format

  markdown:
    cmds:
      - markdownlint --config '.github/lint/.markdownlint.yaml' --ignore-path '.gitignore' *.md **/*.md
    ignore_error: true

  yaml:
    cmds:
      - yamllint --config-file '.github/lint/.yamllint.yaml' .
    ignore_error: true

  format:
    cmds:
      - prettier --config '.github/lint/.prettierrc.yaml' --ignore-path '.gitignore' --check .
    ignore_error: true
