---
version: "3"

tasks:
  all:
    - task: markdown
    - task: yaml
    - task: format

  markdown:
    cmds:
      - mdl -c '.github/lint/.markdownlint.yaml' *.md **/*.md 2>/dev/null
    ignore_error: true

  yaml:
    cmds:
      - yamllint -c '.github/lint/.yamllint.yaml' .
    ignore_error: true

  format:
    cmds:
      - prettier --ignore-path '.github/lint/.prettierignore' --config '.github/lint/.prettierrc.yaml' --check .
    ignore_error: true
