version: '3'

includes:
  gitsecrets: git-secrets/Taskfile_{{OS}}.yml
  talisman: talisman/Taskfile_{{OS}}.yml

tasks:
  setup:
    deps:
      # - install-ggshield
      - git-secrets
      - talisman
  install-ggshield:
    desc: Install ggshield
    cmds:
      - ggshield auth login
    status:
      - ggshield config list | grep token
  git-secrets:
    desc: Setup git-secrets
    deps:
      - gitsecrets:install
    cmds:
      - git secrets --install
      - git secrets --register-aws
    status:
      - cat .git/hooks/commit-msg | grep "git secrets"
  talisman:
    desc: Install talisman
    deps:
      - talisman:install
