on:
  - pull_request
name: 'Tartufo Scan'
jobs:
  tartufo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: godaddy/tartufo-action@c82bd97f0052b12d204d03cea56a5f4667d9c0de # tag=v3.1.4
        id: tartufo
        with:
          entropy: "true"
          regex: "true"
          scan-filenames: "true"
          include-submodule: "false"