on:
  - pull_request
name: 'Tartufo Scan'
jobs:
  tartufo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: godaddy/tartufo-action@7e34fe798485a138ba59ecf533f5a5dd790351bb # tag=v3.2.0
        id: tartufo
        with:
          entropy: "true"
          regex: "true"
          scan-filenames: "true"
          include-submodule: "false"