on:
  - pull_request
name: 'Tartufo Scan'
jobs:
  tartufo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: godaddy/tartufo-action@v3.1.4
        with:
          entropy: "true"
          regex: "true"
          scan-filenames: "true"
          include-submodule: "false"