on:
  - pull_request
name: 'Tartufo Scan'
jobs:
  tartufo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: godaddy/tartufo-action@v3.1.4
        id: tartufo
        with:
          entropy: "true"
          regex: "true"
          scan-filenames: "true"
          include-submodule: "false"
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ### Tartufo Scan Results
            ```
            ${{steps.tartufo.outputs}}
            ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default